apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-dz6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-dz6
  template:
    metadata:
      labels:
        app: auth-service-dz6
    spec:
      containers:
        - name: auth-service
          image: {{ .Values.authService.image }}
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgresql
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: {{ .Values.postgresql.database }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-dz6
spec:
  selector:
    app: auth-service-dz6
  ports:
    - port: 80
      targetPort: 8080 