apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | b64enc }}

