{{- if .Values.zookeeper.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.zookeeper.persistence.storageClass }}
  storageClassName: {{ .Values.zookeeper.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.zookeeper.persistence.size }}
{{- end }} 