apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  type: {{ .Values.zookeeper.service.type }}
  ports:
  - port: {{ .Values.zookeeper.service.port }}
    targetPort: 2181
  selector:
    app: zookeeper 