apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: users-api-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: users-api
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s 