kafka:
  image:
    repository: wurstmeister/kafka
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  persistence:
    enabled: true
    size: 1Gi
    storageClass: ""
  service:
    type: ClusterIP
    port: 9092

zookeeper:
  image:
    repository: zookeeper
    tag: latest
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    size: 1Gi
    storageClass: ""
  service:
    type: ClusterIP
    port: 2181 