apiVersion: apps/v1
kind: Deployment
metadata:
  name: dz4-crud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dz4-crud-app
  template:
    metadata:
      labels:
        app: dz4-crud-app
    spec:
      containers:
      - name: dz4-crud-app
        image: ilyaolshannikov/dz4-crud-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
