apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-job
spec:
  template:
    spec:
      containers:
      - name: flyway-migration
        image: ilyaolshannikov/dz4-migration:latest
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: FLYWAY_URL
          value: "jdbc:postgresql://DB_HOST:DB_PORT/DB_NAME"
        - name: FLYWAY_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
      restartPolicy: OnFailure
