apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-schema
data:
  schema.sql: |
    CREATE TABLE IF NOT EXISTS users (
      id SERIAL PRIMARY KEY,
      email VARCHAR(255) NOT NULL UNIQUE,
      name VARCHAR(255) NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-service-schema
data:
  schema.sql: |
    CREATE TABLE IF NOT EXISTS accounts (
      id SERIAL PRIMARY KEY,
      user_id BIGINT NOT NULL UNIQUE,
      email VARCHAR(255) NOT NULL,
      balance DECIMAL(10,2) NOT NULL DEFAULT 0,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-schema
data:
  schema.sql: |
    CREATE TABLE IF NOT EXISTS notifications (
      id SERIAL PRIMARY KEY,
      user_id BIGINT NOT NULL,
      email VARCHAR(255) NOT NULL,
      message TEXT NOT NULL,
      type VARCHAR(50) NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    ); 