apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: {{ .Values.userService.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: "{{ .Values.userService.image.repository }}:{{ .Values.userService.image.tag }}"
        imagePullPolicy: {{ .Values.userService.image.pullPolicy }}
        ports:
        - containerPort: 3000
        env:
        {{- range $key, $value := .Values.userService.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      initContainers:
      - name: wait-for-postgresql
        image: postgres:14-alpine
        command: ['sh', '-c', 
          'until pg_isready -h postgresql -p 5432 -U postgres; do echo waiting for postgresql; sleep 2; done;']
      - name: init-db
        image: postgres:14-alpine
        command: ['sh', '-c',
          'PGPASSWORD=$POSTGRES_PASSWORD psql -h postgresql -U postgres -d stream_processing -c "$(cat /schema/schema.sql)"']
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        volumeMounts:
        - name: schema
          mountPath: /schema
      volumes:
      - name: schema
        configMap:
          name: user-service-schema
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
  - port: 3000
    targetPort: 3000 